[project]
name = "devpath"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai[groq]",
    "groq",
    "logfire",
    "dlt[duckdb]",
    "minsearch",
    "pdfplumber",
    "onnxruntime",
    "tokenizers",
    "numpy",
    "tqdm",
    "pandas",
    "requests",
    "python-dotenv",
    "beautifulsoup4",
    "fastapi",
    "uvicorn",
    "streamlit",
    "openpyxl",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "kagglehub>=1.0.2",
    "sentence-transformers>=5.7.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true